import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Booking.module.css";
import img from "../public/imagen.jpg";
import logo from "../public/logo.png"
import Link from "next/link";

const booking = () => {
  return (
    <>
      <Head>
        <title>Extensiones Milán Medellín | Reservas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <section className={styles.booking}>
        <div className={styles.img}></div>
        <div className={styles.form}>
          <div className={styles.section_one}>
            <Image src={logo} />
            <div className={styles.name}>Extensiones Milán Medellín</div>
          </div>
          <div className={styles.section_two}>
            <div className={styles.title}>Reserva tu cita</div>
            <div className={styles.data}>
              <div className={styles.doble}>
                <input className={styles.input} type="text" placeholder="Nombres" autoFocus />
                <input className={styles.input} type="text" placeholder="Apellidos" />
              </div>
              <input className={styles.input} type="text" placeholder="Correo electronico" />
              <input className={styles.input} type="text" placeholder="Numero de celular" />
              <div className={styles.doble}>
                <input className={styles.input} type="text" placeholder="C.C" />
                <input className={styles.input} type="date" placeholder="Apellidos" />
              </div>
              <input className={styles.input} type="text" placeholder="Pais" />
              <button className={styles.button}>ENVIAR</button>
            </div>
          </div>

          <div className={styles.text}>
            <div className={styles.home}><Link href="/">Inicio</Link></div>
            <div className={styles.copy}>©2022 | EMM</div>
          </div>
        </div>
      </section>
    </>
  );
};

export default booking;
