import Head from "next/head";
import Banner from "../components/Banner";
import Footer from "../components/Footer";
import Gallery from "../components/Gallery";
import Header from "../components/Header";
import Process from "../components/Process";
import Services from "../components/Services";
import Subscribe from "../components/Subscribe";
import styles from "../styles/Background.module.css"

export default function Home() {
  return (
    <>
      <div className={styles.background}>
      <Head>
        <title>Extensiones Milán Medellín</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Banner />
      <Services />
      <Gallery />
      <Process />
      <Subscribe />
      <Footer />
      </div>
    </>
  );
}
